name: Deploy Latest Mendix App Version

on: 
  push:
    branches:
      - main
      - master
      - acceptance
jobs:
  SetupEnvironment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PW }}
      - name: Setup MinIO Connection
        run: |
          echo "Setting up Minio S3"
        env:
          MINIO_HOST: "dda9-2803-9810-4789-f910-5053-31bf-ce62-445f.ngrok-free.app"
          MINIO_PORT: "443"
          ACCESS_KEY: "LtJeM4dfwVxTQMW9aWCB"
          SECRET_KEY: "Is2mlxK6LNSCyGLoDUGW7vYPTu3idgQQKWuMTmke"

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prep mx-buildack
        uses: actions/checkout@v2
        with:
          repository: 'mendix/docker-mendix-buildpack.git'
          ref: 'latest'
      - name: Setup builders
        run: |
          docker pull josevaldojnr/mendix-rootfs:app
          docker pull josevaldojnr/mendix-rootfs:build
          docker run josevaldojnr/mendix-rootfs:app
          docker run josevaldojnr/mendix-rootfs:build

      - name : Build and push the image
        run: |
          git clone -b master https://github.com/josevaldojnr/OnPremisesApp.git
          python build.py --destination tmp/image --source OnPremisesApp/OnPremisesApp.mpr build-mda-dir
          docker build \
          --build-arg ROOTFS_IMAGE=josevaldojnr/mendix-rootfs:app \
          --build-arg BUILD_IMAGE=josevaldojnr/mendix-rootfs:build \
          -t josevaldojnr/on_premises_app:latest \
          tmp/image
          docker push josevaldojnr/mendix_onpremise:latest
          